### ISSUE TITLE
Confusing function: depositTransaction

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/tokamak-thanos#211]
**Describe the background**
Optimism provides two functions: depositTransaction and depositERC20Transaction.
- depositTransaction: Used when ether is a native token
- depositERC20Transaction: Used when the ERC20 token is a native token
```
function depositTransaction(
 address_to;
 uint256_value,   /// The value represents ether
 uint64 _gasLimit;
 bool _isCreation;   
 bytes memory_data
 ) 

function depositERC20Transaction(
 address_to,
 uint256 _mint,
 uint256_value,     /// The value represents the amount of ERC20.
 uint64 _gasLimit;
 bool _isCreation;
 bytes memory_data
 ) 
```
In Thanos, among the above functions, the depositTransaction function is used, and the depositERC20Transaction function is not exist.
```
function depositTransaction(
        address _to,
        uint256 _mint,
        uint256 _value,  /// the value is processed as TON (L2 native token), unlike Optimism.
        uint64 _gasLimit,
        bool _isCreation,
        bytes calldata _data
    )
```
**Problem**
Thanos uses ERC20 tokens as native tokens, and I think it may be confusing reasons below.
- users are familiar with Optimism
- upgrading along with Optimism's future upgrades 
- using the SDK produced by Optimism

**What I suggest** 
I suggest changing Thanos' depositTransaction function name to depositERC20Transaction.
(question) Are there cases where _mint parameter and _value parameter are different? If the mint and value values ​​must always be the same, I recommend deleting the mint parameter.
```
function depositERC20Transaction(
        address _to, 
        uint256 _value,             /// the value is processed as TON (L2 native token), unlike Optimism.
        uint64 _gasLimit,
        bool _isCreation,
        bytes calldata _data
    )
```

**Comment by nguyenzung** [comment]
Hi @Zena-park ,

Thank you for your opinion!

1. It is possible for the case that _mint != _value. 
2. For the function name, the reason Optimism's supports both **depositTransaction** and **depositERC20Transaction** is the support of configuring L2 Native token as ETH or an ERC20. Thanos supports only ERC20 token so **depositTransaction** make sense to me because it indicates that the function is for depositing in general. The term **depositERC20Transaction** probably makes users think about depositing ERC20 token to L2 and on L2, we also receive ERC20 token. The Custom Gas Token feature is not stable and even if they use depositERC20Transaction, we can still easily upgrade Thanos because it is just a function name. 

So in my personal opinion, it is better to keep the current interface

**Comment by Zena-park** [comment]
Hi @nguyenzung 
(1) It is not clear whether the **depositTransaction** function you proposed also receives a native token (TON) as input. This is because you already receive ETH from Optimism. Actually, I was very confused.
(2) Thanos’ **depositERC20Transaction, which I proposed**, is designed so that no other tokens can be received. If the user misunderstood that they were giving an ERC20 token, the token address must be entered in the parameter, but there is no interface to enter the token address, and the native token must be approved in advance, but since it was not approved, the function cannot be executed.
(3) If there is still confusion about the depositERC20Transaction function name, it may be more appropriate to use another name that does not confusion.

**Comment by Zena-park** [comment]
@nguyenzung 

`It is possible for the case that _mint != _value.`
Can you give an example of when _mint != _value should be used? I still don't understand exactly what the case is.

**Comment by nguyenzung** [comment]
> Hi @nguyenzung
> 
> (1) It is not clear whether the **depositTransaction** function you proposed also receives a native token (TON) as input. This is because It already receives ETH from Optimism. Actually, I was very confused.
> 
> (2) Thanos’ **depositERC20Transaction, which I proposed**, is designed so that no other tokens can be received. If the user misunderstood that they were giving an ERC20 token, the token address must be entered in the parameter, but there is no interface to enter the token address, and the native token must be approved in advance, but since it was not approved, the function cannot be executed. Also, this is already used in Optimism.
> 
> (3) If there is still confusion about the depositERC20Transaction function name, it may be more appropriate to use another name that does not confusion.

Thank you, Zena!

I think it is okay to me. How about making vote on it? 

About _mint and _value:
- _mint: The balance of the L1-deposit's sender on L2 will increase the amount of _mint
- _value: this is used for making a transaction on L2
For example: User A can make one deposit transaction to do 2 things
- Increase his/her balance on L2 with _mint 
- Call a smart contract 's function on L2 with _value is the callvalue of the L2's transaction

**Comment by Zena-park** [comment]
@nguyenzung 
I understand !!  Thank you for providing detailed information. :bow: :+1:
If so, it's nothing to vote. As you said, mint and value are different things, so they must be separate parameters. 

Let me ask you just one more question.
Two transactions go at once, but if there is not enough value in L2, does mint succeed and only the transaction fail?

**Comment by Zena-park** [comment]
@nguyenzung 
As for the issue of depositERC20Transaction and depositTransaction names, as you said, I think you can decide after listening to the opinions of other members.

Then, the function name I suggest is depositERC20Transaction, which is the same as Optimism.
```
function depositERC20Transaction(
 address_to,
 uint256 _mint,
 uint256_value, /// The value represents the amount of native token TON.
 uint64_gasLimit;
 bool _isCreation;
 bytes memory_data
 )
```

**Comment by nguyenzung** [comment]
> @nguyenzung I understand !! Thank you for providing detailed information. 🙇 👍 As you said, mint and value are different things, so they must be separate parameters.
> 
> Let me ask you just one more question. Two transactions go at once, but if there is not enough value in L2, does mint succeed and only the transaction fail?

Yes, you are right. The L2 sender's balance increase but the tx fail.

**Comment by nguyenzung** [comment]
> @nguyenzung As for the issue of depositERC20Transaction and depositTransaction names, as you said, I think you can decide after listening to the opinions of other members.
> 
> Then, the function name I suggest is depositERC20Transaction, which is the same as Optimism.
> 
> ```
> function depositERC20Transaction(
>  address_to,
>  uint256 _mint,
>  uint256_value, /// The value represents the amount of native token TON.
>  uint64_gasLimit;
>  bool _isCreation;
>  bytes memory_data
>  )
> ```

That's what I mean. I think the decision on the function name belongs to personal opinions in this case between **depositTransaction** and **depositERC20Transaction**. Let wait more opinion on the function names.

**Comment by boohyung** [comment]
I think it's entirely a matter of choice rather than logic. We are designed to deposit using only one function. So I think we keep it now. (Use `depositTransaction`). I don't think there will be any unnecessary confusion for users who realize that Thanos can use ERC20 assets as native tokens.

**Comment by Zena-park** [comment]
Yes, I understand.
For users who are familiar with the Tokamak Guide and Specification documents, this should not be a problem at all.
Thanks for your reply.
I will close the issue.
