### ISSUE TITLE
Add L2 chain identifier to paused() implementation

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/tokamak-thanos#213]
The paused() function is calling superchainConfig.paused().
If you later plan to manage multiple chains in superchainConfig,
It seems appropriate to add identifier of l2 chain.
superchainConfig.paused() -> superchainConfig.paused(identifier of L2 chain).
```
/// @inheritdoc CrossDomainMessenger
    function paused() public view override returns (bool) {
        return superchainConfig.paused();
    }

--> 

/// @inheritdoc CrossDomainMessenger
    function paused() public view override returns (bool) {
        return superchainConfig.paused(identifier of L2 chain);
    }

```

**Comment by nguyenzung** [comment]
Thank you

Let discuss it as an improvement that is outside of L2 native token scope.

**Comment by suahnkim** [comment]
@Zena-park I think this should be part of Thanos code as we will probably use the same code base for L2 on demand and beyond. However, I think we do not have enough information to add this part yet as the policy is not set. 

Can we close this issue for now and come back to it later?

**Comment by Zena-park** [comment]
Yes, I understand. I'll close the issue.
