### ISSUE TITLE
Deleting bridgeETH and bridgeETHTo function's unnecessary parameters

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/tokamak-thanos#232]
The amount parameter value of bridgeETH and bridgeETHTo can be replaced with msg.value, so it is an unnecessary parameter.
 
 - bridgeETH
 https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/universal/StandardBridge.sol#L214-L215
 
```
 function bridgeETH(uint32 _minGasLimit, bytes calldata _extraData) public payable onlyEOA {
        _initiateBridgeETH(msg.sender, msg.sender, msg.value, _minGasLimit, _extraData);
 }
```
- bridgeETHTo 
https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/universal/StandardBridge.sol#L230-L231
 
 ```
 function bridgeETHTo(address _to, uint32 _minGasLimit, bytes calldata _extraData) public payable {
        _initiateBridgeETH(msg.sender, _to, msg.value, _minGasLimit, _extraData);
 }
```

**Comment by nguyenzung** [comment]
Hi @Zena-park 

This function can also e used on L2. On L2, we cannot use msg.value because ETH is not native token on L2. So I think it is better for keeping this interface.

**Comment by Zena-park** [comment]
I understand.

Then I will close this issue.
