### ISSUE TITLE
(Question) What happens if I withdraw the L2 WNativeToken?

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/tokamak-thanos#234]
WNativeToken of L2 is also an ERC20 token.

What happens if I withdraw the L2's [WNativeToken](https://explorer.thanos-sepolia.tokamak.network/address/0x4200000000000000000000000000000000000006?tab=contract_code) (0x4200000000000000000000000000000000000006)?

- Can I normally bring TON(nativeToken) to L1? 
- Can I not execute the transaction as a reverting transaction?

**Comment by nguyenzung** [comment]
Hi @Zena-park 

In L2, TON is equivalent to ETH on L1. L2'TON is not an ERC20 token. So we have WNativeToken with the same role as L1's WETH. 

So one way we can do is swaping WNativeToken to L2 Native Token then withdraw to L1

**Comment by Zena-park** [comment]
According to your answer, if I execute the above case, I will lose the L2's WNativeToken that I requested a withdrawal?

**Comment by nguyenzung** [comment]
Yes, you are right. You will lose token. It is a normal cases. In Optimism as well, if we withdraw an arbitrary token, it is possible for losing token. There is nothing different compared to Optimism

**Comment by Zena-park** [comment]
Thanks for your reply. I will close the issue.
