### ISSUE TITLE
Questions about initialize function

### ISSUE THREAD

**Issue by zzooppii** [tokamak-network/tokamak-thanos#238]
The initialize function is designed to be used once and then never used again. 

Are the values ​​of superchainConfig and systemConfig not going to change in the future?

https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/contracts-bedrock/src/L1/L1StandardBridge.sol#L87-L93

And since the permission for initialize is public, I wonder when the initialize is performed after the contract is distributed.

**Comment by nguyenzung** [comment]
Hi @zzooppii 

I think the modifier initializer make sure the initialize will be called one time

**Comment by zzooppii** [comment]
And since the permission for initialize is public, I wonder when the initialize is performed after the contract is deployed.

**Comment by nguyenzung** [comment]
This function must be called when setting implementation by using upgradeAndCall. So it is safe

**Comment by zzooppii** [comment]
okay thank you
