### ISSUE TITLE
Useless storage variable in `OptimismPortal`

### ISSUE THREAD

**Issue by mehdi-defiesta** [tokamak-network/tokamak-thanos#248]
**Describe the bug**
```depositedAmount``` is not used for calculation. No need to implement it

**Configuration**
- Severity: Gas optimization

**Impact**
waste of gas

**Recommendation**
deleting the variable

**Comment by nguyenzung** [comment]
Thank you @mehdi-defiesta 

I fixed the issue here: https://github.com/tokamak-network/tokamak-thanos/commit/1f974febe8f2992691a349048572a57f4aa4ae57

**Comment by mehdi-defiesta** [comment]
I close the issue then. Thank you @nguyenzung
