### ISSUE TITLE
Using transfer instead of approve in OptimismPortal

### ISSUE THREAD

**Issue by nguyenzung** [tokamak-network/tokamak-thanos#252]
SEREViTY: MEDIUM

IMPACT: a withdrawal transaction can be finalized with unexpected amount

**Comment by rlgns98kr** [comment]
I think it's a great idea.
We can prevent to manipulate other target's allowance in the Portal!
Because L1CDM's relayMessage permits only the Portal Contract, I think it makes sense!

**Comment by nguyenzung** [comment]
As what discussed with @rlgns98kr , we can close this issue and waiting for the discussion with the audit team in the external audit
