### ISSUE TITLE
Analysis of the current implementation of L2 native token feature (specifically OptimismPortal, L1crossDomainMessenger)

### ISSUE THREAD

**Issue by suahnkim** [tokamak-network/tokamak-thanos#253]
Please check previous thread for complete information
- issue raised: https://github.com/tokamak-network/tokamak-thanos/issues/243
- call log 1: https://github.com/tokamak-network/tokamak-thanos/issues/243#issuecomment-2327686224 
- call log 2: https://github.com/tokamak-network/tokamak-thanos/issues/243#issuecomment-2330402879

**Pros of current implementation of L2 native token:**
- Calls the transfer (withdraw) of native token from L1StandardBridge, making the system more consistent (does not bypass L1CrossDomainMessenger like Optimism's custom gas token)
- DepositTransaction is reserved for L2 native token only, which prevents unexpected flow on L2

**Cons of current implementation of L2 native token:**
- Need to communicate with developers that L2 sendMessage doesn't automatically transfer the L2 native token on L1 to the target address. Should provide an example snippet from L1StandardBridge.
- Higher gas costs for L2 native token messaging from L2, as the token must be transferred across multiple contracts (OptimismPortal -> L1CrossDomainMessenger -> L1StandardBridge -> target)
  - This approach offers an advantage: The L2 native token passes through the L1CrossDomainMessenger when finalizing withdrawals, mirroring ETH's path in Optimism's version without the custom gas token activated. In contrast, when Optimism's custom gas token is active, it bypasses the L1CrossDomainMessenger during withdrawal finalization  (OptimismPortal -> target).
- Use of approval on arbitrary addresses (This may not be a con, as it might not be an issue)
  - While it doesn't seem to be an issue currently, we may need to conduct further checks (reentrancy issues has been checked)

**Additional considerations:**
- Transaction atomicity for L2 native token value and ETH messaging is lost in RelayMessage (This isn't necessarily a con, as it's the same for Optimism's custom gas token implementation as well)
  - DApps that depend on and expect atomicity can't rely on it. However, creating an atomic system could be challenging and potentially introduce security vulnerabilities we haven't considered. This may be an impossible task (if we prioritize security) due to the differences between ERC20 tokens and ETH

**Conclusion:**
- Overall, I believe the current version's pros outweigh its cons. It provides sufficient distinction from custom gas tokens without breaking compatibility with existing OP node software, which is a significant achievement.

**Resolution:**
After discussion with Foundation about the pros and cons, this issue will be updated.

If there is any misinformation or missing information, please include in this thread.

**Comment by nguyenzung** [comment]
@suahnkim Which version did you compare to Thanos? Optimism with ETH as native token on L2 or Custom Gas Token

**Comment by suahnkim** [comment]
> @suahnkim Which version did you compare to Thanos? Optimism with ETH as native token on L2 or Custom Gas Token

@nguyenzung the comparison is between Thanos and Optimism (when custom gas token is activated, where ETH is not the L2’s native currency)

If I've made any errors in my writing, please point them out and provide the correct information.

**Comment by suahnkim** [comment]
@nguyenzung I think I understand which part was not clear:
 
_But this is also a pro, as it preserves the movement of the L2 native token (when compared with ETH unlike Optimism's custom gas token)_

-> This part has been updated to 
"This approach offers an advantage: The L2 native token passes through the L1CrossDomainMessenger when finalizing withdrawals, mirroring ETH's path in Optimism's version without the custom gas token activated. In contrast, when Optimism's custom gas token is active, it bypasses the L1CrossDomainMessenger during withdrawal finalization."

**Comment by nguyenzung** [comment]
Thank you for your clarification, @suahnkim 

I just don't really understand the purpose of this issue, and the comparison information for the issue based on what? 
What are we going to solve for this issue? What are we going to analyze? When this issue is closed, what is the next step?
I will also put a call log from my view of point for the last 2 calls

**Comment by suahnkim** [comment]
This is not an issue.
It is a record keeping in case we need to discuss about the direction.


Since we are pushing our development more open and we have several choices, it is essential to have a single location where other developers can look at what kind of discussion we've had when developing the code

**Comment by nguyenzung** [comment]
Continue checking: https://github.com/tokamak-network/tokamak-thanos/issues/237

**Comment by 0x6e616d** [comment]
The external audit is finished so I think we can close this issue.
